package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccesoId generated by hbm2java
 */
@Embeddable
public class AccesoId implements java.io.Serializable {

	private int CPerfil;
	private int CAcceso;

	public AccesoId() {
	}

	public AccesoId(int CPerfil, int CAcceso) {
		this.CPerfil = CPerfil;
		this.CAcceso = CAcceso;
	}

	@Column(name = "C_PERFIL", nullable = false)
	public int getCPerfil() {
		return this.CPerfil;
	}

	public void setCPerfil(int CPerfil) {
		this.CPerfil = CPerfil;
	}

	@Column(name = "C_ACCESO", nullable = false)
	public int getCAcceso() {
		return this.CAcceso;
	}

	public void setCAcceso(int CAcceso) {
		this.CAcceso = CAcceso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccesoId))
			return false;
		AccesoId castOther = (AccesoId) other;

		return (this.getCPerfil() == castOther.getCPerfil())
				&& (this.getCAcceso() == castOther.getCAcceso());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCPerfil();
		result = 37 * result + this.getCAcceso();
		return result;
	}

}
