package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Acceso generated by hbm2java
 */
@Entity
@Table(name = "acceso", catalog = "bd_bastanteo")
public class Acceso implements java.io.Serializable {

	private AccesoId id;
	private Perfil perfil;
	private String nombre;
	private String orden;
	private String urlAcceso;

	public Acceso() {
	}

	public Acceso(AccesoId id, Perfil perfil, String nombre, String orden,
			String urlAcceso) {
		this.id = id;
		this.perfil = perfil;
		this.nombre = nombre;
		this.orden = orden;
		this.urlAcceso = urlAcceso;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "CPerfil", column = @Column(name = "C_PERFIL", nullable = false)),
			@AttributeOverride(name = "CAcceso", column = @Column(name = "C_ACCESO", nullable = false)) })
	public AccesoId getId() {
		return this.id;
	}

	public void setId(AccesoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PERFIL", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "NOMBRE", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ORDEN", nullable = false, length = 11)
	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	@Column(name = "URL_ACCESO", nullable = false, length = 100)
	public String getUrlAcceso() {
		return this.urlAcceso;
	}

	public void setUrlAcceso(String urlAcceso) {
		this.urlAcceso = urlAcceso;
	}

}
