package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DBastanteoGrupoId generated by hbm2java
 */
@Embeddable
public class DBastanteoGrupoId implements java.io.Serializable {

	private String CEmpresa;
	private int CGrupoBastanteo;
	private String CPoder;

	public DBastanteoGrupoId() {
	}

	public DBastanteoGrupoId(String CEmpresa, int CGrupoBastanteo, String CPoder) {
		this.CEmpresa = CEmpresa;
		this.CGrupoBastanteo = CGrupoBastanteo;
		this.CPoder = CPoder;
	}

	@Column(name = "C_EMPRESA", nullable = false, length = 8)
	public String getCEmpresa() {
		return this.CEmpresa;
	}

	public void setCEmpresa(String CEmpresa) {
		this.CEmpresa = CEmpresa;
	}

	@Column(name = "C_GRUPO_BASTANTEO", nullable = false)
	public int getCGrupoBastanteo() {
		return this.CGrupoBastanteo;
	}

	public void setCGrupoBastanteo(int CGrupoBastanteo) {
		this.CGrupoBastanteo = CGrupoBastanteo;
	}

	@Column(name = "C_PODER", nullable = false, length = 4)
	public String getCPoder() {
		return this.CPoder;
	}

	public void setCPoder(String CPoder) {
		this.CPoder = CPoder;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DBastanteoGrupoId))
			return false;
		DBastanteoGrupoId castOther = (DBastanteoGrupoId) other;

		return ((this.getCEmpresa() == castOther.getCEmpresa()) || (this
				.getCEmpresa() != null
				&& castOther.getCEmpresa() != null && this.getCEmpresa()
				.equals(castOther.getCEmpresa())))
				&& (this.getCGrupoBastanteo() == castOther.getCGrupoBastanteo())
				&& ((this.getCPoder() == castOther.getCPoder()) || (this
						.getCPoder() != null
						&& castOther.getCPoder() != null && this.getCPoder()
						.equals(castOther.getCPoder())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCEmpresa() == null ? 0 : this.getCEmpresa().hashCode());
		result = 37 * result + this.getCGrupoBastanteo();
		result = 37 * result
				+ (getCPoder() == null ? 0 : this.getCPoder().hashCode());
		return result;
	}

}
