package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * DBastanteoGrupo generated by hbm2java
 */
@Entity
@Table(name = "d_bastanteo_grupo", catalog = "bd_bastanteo")
public class DBastanteoGrupo implements java.io.Serializable {

	private DBastanteoGrupoId id;
	private Bastanteo bastanteo;
	private GrupoBastanteo grupoBastanteo;

	public DBastanteoGrupo() {
	}

	public DBastanteoGrupo(Bastanteo bastanteo, GrupoBastanteo grupoBastanteo) {
		this.bastanteo = bastanteo;
		this.grupoBastanteo = grupoBastanteo;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "CEmpresa", column = @Column(name = "C_EMPRESA", nullable = false, length = 8)),
			@AttributeOverride(name = "CGrupoBastanteo", column = @Column(name = "C_GRUPO_BASTANTEO", nullable = false)),
			@AttributeOverride(name = "CPoder", column = @Column(name = "C_PODER", nullable = false, length = 4)) })
	public DBastanteoGrupoId getId() {
		return this.id;
	}

	public void setId(DBastanteoGrupoId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Bastanteo getBastanteo() {
		return this.bastanteo;
	}

	public void setBastanteo(Bastanteo bastanteo) {
		this.bastanteo = bastanteo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "C_EMPRESA_FK", referencedColumnName = "C_EMPRESA", nullable = false),
			@JoinColumn(name = "C_GRUPO_BASTANTEO_FK", referencedColumnName = "C_GRUPO_BASTANTEO", nullable = false) })
	public GrupoBastanteo getGrupoBastanteo() {
		return this.grupoBastanteo;
	}

	public void setGrupoBastanteo(GrupoBastanteo grupoBastanteo) {
		this.grupoBastanteo = grupoBastanteo;
	}

}
