package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrupoBastanteoId generated by hbm2java
 */
@Embeddable
public class GrupoBastanteoId implements java.io.Serializable {

	private String CEmpresa;
	private int CGrupoBastanteo;

	public GrupoBastanteoId() {
	}

	public GrupoBastanteoId(String CEmpresa, int CGrupoBastanteo) {
		this.CEmpresa = CEmpresa;
		this.CGrupoBastanteo = CGrupoBastanteo;
	}

	@Column(name = "C_EMPRESA", nullable = false, length = 8)
	public String getCEmpresa() {
		return this.CEmpresa;
	}

	public void setCEmpresa(String CEmpresa) {
		this.CEmpresa = CEmpresa;
	}

	@Column(name = "C_GRUPO_BASTANTEO", nullable = false)
	public int getCGrupoBastanteo() {
		return this.CGrupoBastanteo;
	}

	public void setCGrupoBastanteo(int CGrupoBastanteo) {
		this.CGrupoBastanteo = CGrupoBastanteo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrupoBastanteoId))
			return false;
		GrupoBastanteoId castOther = (GrupoBastanteoId) other;

		return ((this.getCEmpresa() == castOther.getCEmpresa()) || (this
				.getCEmpresa() != null
				&& castOther.getCEmpresa() != null && this.getCEmpresa()
				.equals(castOther.getCEmpresa())))
				&& (this.getCGrupoBastanteo() == castOther.getCGrupoBastanteo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCEmpresa() == null ? 0 : this.getCEmpresa().hashCode());
		result = 37 * result + this.getCGrupoBastanteo();
		return result;
	}

}
