package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "bd_bastanteo")
public class Perfil implements java.io.Serializable {

	private int CPerfil;
	private String nombre;
	private Character flagActivo;
	//private Set usuarios = new HashSet(0);
	//private Set accesos = new HashSet(0);

	public Perfil() {
	}

	public Perfil(int CPerfil, String nombre) {
		this.CPerfil = CPerfil;
		this.nombre = nombre;
	}
/*
	public Perfil(int CPerfil, String nombre, Character flagActivo,
			Set usuarios, Set accesos) {
		this.CPerfil = CPerfil;
		this.nombre = nombre;
		this.flagActivo = flagActivo;
		this.usuarios = usuarios;
		this.accesos = accesos;
	}
*/
	
	@Id
	@Column(name = "C_PERFIL", unique = true, nullable = false)
	public int getCPerfil() {
		return this.CPerfil;
	}

	public void setCPerfil(int CPerfil) {
		this.CPerfil = CPerfil;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "FLAG_ACTIVO", length = 1)
	public Character getFlagActivo() {
		return this.flagActivo;
	}

	public void setFlagActivo(Character flagActivo) {
		this.flagActivo = flagActivo;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}
*/
	
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set getAccesos() {
		return this.accesos;
	}

	public void setAccesos(Set accesos) {
		this.accesos = accesos;
	}
	
	*/

}
