package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poder generated by hbm2java
 */
@Entity
@Table(name = "poder", catalog = "bd_bastanteo")
public class Poder implements java.io.Serializable {

	private String CPoder;
	private String nombre;
	private char tipoPoder;
	//private Set bastanteos = new HashSet(0);

	public Poder() {
	}

	public Poder(String CPoder, String nombre, char tipoPoder) {
		this.CPoder = CPoder;
		this.nombre = nombre;
		this.tipoPoder = tipoPoder;
	}
/*
	public Poder(String CPoder, String nombre, char tipoPoder, Set bastanteos) {
		this.CPoder = CPoder;
		this.nombre = nombre;
		this.tipoPoder = tipoPoder;
		this.bastanteos = bastanteos;
	}
*/
	@Id
	@Column(name = "C_PODER", unique = true, nullable = false, length = 4)
	public String getCPoder() {
		return this.CPoder;
	}

	public void setCPoder(String CPoder) {
		this.CPoder = CPoder;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "TIPO_PODER", nullable = false, length = 1)
	public char getTipoPoder() {
		return this.tipoPoder;
	}

	public void setTipoPoder(char tipoPoder) {
		this.tipoPoder = tipoPoder;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poder")
	public Set getBastanteos() {
		return this.bastanteos;
	}

	public void setBastanteos(Set bastanteos) {
		this.bastanteos = bastanteos;
	}
*/
}
