package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RepresentanteId generated by hbm2java
 */

@Embeddable
public class RepresentanteId implements java.io.Serializable {

	private String CEmpresa;
	private int CRepresentante;

	public RepresentanteId() {
	}

	public RepresentanteId(String CEmpresa, int CRepresentante) {
		this.CEmpresa = CEmpresa;
		this.CRepresentante = CRepresentante;
	}

	@Column(name = "C_EMPRESA", nullable = false, length = 8)
	public String getCEmpresa() {
		return this.CEmpresa;
	}

	public void setCEmpresa(String CEmpresa) {
		this.CEmpresa = CEmpresa;
	}

	@Column(name = "C_REPRESENTANTE", nullable = false)
	public int getCRepresentante() {
		return this.CRepresentante;
	}

	public void setCRepresentante(int CRepresentante) {
		this.CRepresentante = CRepresentante;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RepresentanteId))
			return false;
		RepresentanteId castOther = (RepresentanteId) other;

		return ((this.getCEmpresa() == castOther.getCEmpresa()) || (this
				.getCEmpresa() != null
				&& castOther.getCEmpresa() != null && this.getCEmpresa()
				.equals(castOther.getCEmpresa())))
				&& (this.getCRepresentante() == castOther.getCRepresentante());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCEmpresa() == null ? 0 : this.getCEmpresa().hashCode());
		result = 37 * result + this.getCRepresentante();
		return result;
	}

}
