package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoIntervencion generated by hbm2java
 */
@Entity
@Table(name = "tipo_intervencion", catalog = "bd_bastanteo")
public class TipoIntervencion implements java.io.Serializable {

	private int CTipoIntervencion;
	private String nombre;
	private Set bastanteos = new HashSet(0);

	public TipoIntervencion() {
	}

	public TipoIntervencion(int CTipoIntervencion, String nombre) {
		this.CTipoIntervencion = CTipoIntervencion;
		this.nombre = nombre;
	}

	public TipoIntervencion(int CTipoIntervencion, String nombre, Set bastanteos) {
		this.CTipoIntervencion = CTipoIntervencion;
		this.nombre = nombre;
		this.bastanteos = bastanteos;
	}

	@Id
	@Column(name = "C_TIPO_INTERVENCION", unique = true, nullable = false)
	public int getCTipoIntervencion() {
		return this.CTipoIntervencion;
	}

	public void setCTipoIntervencion(int CTipoIntervencion) {
		this.CTipoIntervencion = CTipoIntervencion;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIntervencion")
	public Set getBastanteos() {
		return this.bastanteos;
	}

	public void setBastanteos(Set bastanteos) {
		this.bastanteos = bastanteos;
	}

}
