package bastanteo.cloud.bean;

// Generated 08/11/2011 11:03:59 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEmpresa generated by hbm2java
 */
@Entity
@Table(name = "tipo_empresa", catalog = "bd_bastanteo")
public class TipoEmpresa implements java.io.Serializable {

	private int CTipoEmpresa;
	private String nombre;
	private String abreviatura;
	private Set<Empresa> empresas = new HashSet<Empresa>(0);

	public TipoEmpresa() {
	}

	public TipoEmpresa(int CTipoEmpresa, String nombre, String abreviatura) {
		this.CTipoEmpresa = CTipoEmpresa;
		this.nombre = nombre;
		this.abreviatura = abreviatura;
	}

	public TipoEmpresa(int CTipoEmpresa, String nombre, String abreviatura,
			Set empresas) {
		this.CTipoEmpresa = CTipoEmpresa;
		this.nombre = nombre;
		this.abreviatura = abreviatura;
		this.empresas = empresas;
	}

	@Id
	@Column(name = "C_TIPO_EMPRESA", unique = true, nullable = false)
	public int getCTipoEmpresa() {
		return this.CTipoEmpresa;
	}

	public void setCTipoEmpresa(int CTipoEmpresa) {
		this.CTipoEmpresa = CTipoEmpresa;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ABREVIATURA", nullable = false, length = 15)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEmpresa")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

}
